sudo: required
services:
    - docker

before_install:
    - docker build -t danielsdockerthing/docker-react -f Dockerfile.dev .

# Commands the need to be executed to run out test suite
script:
    - docker run -e CI=true danielsdockerthing/docker-react npm run test